### ISSUE TITLE
OPEN DISCUSSION: Decide on definitive way to do licenses

### ISSUE THREAD

**Issue by sjfricke** [aleksandar-todorovic/awesome-c#51]
#49 Brought up a good pointing the licenses to direct project license or point to some official documentation about it

For things like the MIT license, one can say that it should be the same because if a project alters it then its a variation of the MIT license and should be noted as so

I also agree with the idea of pointing right to the repo as a license could change and its right to the source. This already happens where someone realizes the license is wrong.

For the argument of the link breaking, the TravisCL will catch it on the next merge it breaks

The only thing is that all the current repos don't have links so those would ideally want to be added and edited then

I don't think file size should be an issue, the readme is only 1000 lines at the moment and a basic text editor can *easily* handle that on any modern computer

**Comment by sjfricke** [comment]
For the records, I am in support of moving towards just pointing to the license in the repo by default as the new standard.

**Comment by firecrypt** [comment]
In addition, I would propose that for each project, the license link be tagged with a `LIC` or `L` prefix. For example: `[Project Name][xxx] - Description [[License Name][LICxxx]`

**Comment by firecrypt** [comment]
I would be willing to execute on this issue once a consensus is reached.

**Comment by sjfricke** [comment]
I am gonna give it a good week for any other opinions and then I would be happy to help as well

**Comment by sjfricke** [comment]
@firecrypt 
So decided with no other input to go with your suggestion and added `LIC` to all license links. I am about to update the Contribution readme, but I plan to slowly transfer all current links over to the license link on the project instead of the generic link as that honestly makes the most sense. Happy with any PR you want/can help with that!

Thanks again for the idea
