### ISSUE TITLE
typo in "Learning, Reference and Tutorials"

### ISSUE THREAD

**Issue by siriusdemon** [aleksandar-todorovic/awesome-c#55]
Learning, Reference and Tutorials
-> Physical 
---->    Beginner 
--------> C Programming: A modern Approach - Excellent book to learn the basics from C **_from_**.

Hi, In sentence "Excellent book to learn the basics from C **_from_**." , is the last _**from**_ redundant?

**Comment by sjfricke** [comment]
Hey, Good eye! [Made changes](https://github.com/aleksandar-todorovic/awesome-c/commit/12e01d7a8092d03540b089c5731f957d86eae257)

Thanks again
