### ISSUE TITLE
Possible change from footer links to inline links

### ISSUE THREAD

**Issue by aleksandar-todorovic** [aleksandar-todorovic/awesome-c#62]
"Links at the bottom" rule was inherited once this list was forked from its original creator.

So far, this practice seems quite counterproductive and a huge waste of everyone's time (especially during the verification phase of a pull request).

Therefore, I propose we change them to inline links.

Of course, this isn't gonna be an easy task at this stage, since there's ~500 links that would need to be relocated, but I think that doing so would save everyone's time.

@sjfricke any thoughts?

Any volunteers? Does anyone know of any tool that would make this switch relatively easy to accomplish?

**Comment by sjfricke** [comment]
@aleksandar-todorovic 
Ya, I felt the whole LatB (Links at the Bottom) method was different and like you said just went with it. I would totally be able to write a little script this weekend to fix it up. The nice part is Travis-CI will catch any small mistakes of bad links.

**Comment by sjfricke** [comment]
Also I hate the fragmentation of numbers as well.... ya **totally** for changing it now

**Comment by sjfricke** [comment]
Everything looks fine now, I also realized when doing this that the format we were using did't allow a way to show that there were 20 unused links in the bottom section.... I really am glad we finally just redid that system
