### ISSUE TITLE
Change License style

### ISSUE THREAD

**Issue by sjfricke** [aleksandar-todorovic/awesome-c#76]
Proposing to change it so instead of 

[[MIT](https://spdx.org/licenses/MIT.html)]

We have it look like

[``MIT``](https://spdx.org/licenses/MIT.html)

Can write a script to find/replace

**Comment by sjfricke** [comment]
@aleksandar-todorovic

**Comment by aleksandar-todorovic** [comment]
Yup, I'm totally fine with that.
